sqlite3:
  adapter: sqlite3
  database: record_history.sqlite3.db
sqlite3mem:
  adapter: sqlite3
  database: ":memory:"
postgresql:
  adapter: postgresql
  username: developer
  password: 
  database: record_history_plugin_test
  min_messages: ERROR
mysql:
  adapter: mysql2
  host: localhost
  username: developer
  password:
  database: record_history_plugin_test
